version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  
# jobs:
#   build:
#     executor: docker/docker
#     steps:
#       - checkout:
#           path: 
      


  

workflows:
  build-push-to-dockerhub:
    jobs:
      - docker/publish:
          image: $DOCKER_USERNAME/$APP_NAME-api-service
          tag: $CIRCLE_SHA1,latest
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USERNAME
          docker-context: ./api-service
          path: ./api-service

      - docker/publish:
          image: $DOCKER_USERNAME/$APP_NAME-chat-service
          tag: $CIRCLE_SHA1,latest
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USERNAME
          docker-context: ./chat-service
          path: ./chat-service

      - docker/publish:
          image: $DOCKER_USERNAME/$APP_NAME-frontend
          tag: $CIRCLE_SHA1,latest
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USERNAME
          docker-context: ./frontend
          path: ./frontend
        


  