version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  
# jobs:
#   build:
#     executor: docker/docker
#     steps:
#       - checkout:
#           path: 
      


  

workflows:
  build-push-to-dockerhub:
    jobs:
      - docker/publish:
          image: $DOCKER_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USERNAME
          docker-context: ./api-service

      - docker/publish:
          image: $DOCKER_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USERNAME
          docker-context: ./chat-service

      - docker/publish:
          image: $DOCKER_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USERNAME
          docker-context: ./frontend
        


  